### ISSUE TITLE
Initializer changes dtype of Parameters

### ISSUE THREAD

**Issue by jgygax** [fmi-basel/stork#13]
The initializers initializes parameters as torch.float32. It would be nice, if it could be consistent with the dtype chosen in the model

**Comment by fzenke** [comment]
Great idea.

**Comment by JRBCH** [comment]
Good catch, I didn't think about that when coding this up. Will have a look at it

**Comment by JRBCH** [comment]
Pull request #14 should provide a quick fix for this. 

The initializer class cannot inherit the `dtype` from the connection objects, because they are usually only assigned after model.configure() is called, which we typically do after initialization. 

So I added a `dtype` attribute to the Initializer base class that will be considered by every inheriting initializer.
